---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2017 Ericsson AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- hosts: opnfv
  remote_user: root
  vars_files:
    - "{{ xci_path }}/xci/var/opnfv.yml"
    - "{{ xci_path }}/xci/installer/osa/files/openstack_services.yml"

  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"
    https_proxy: "{{ lookup('env','https_proxy') }}"
    no_proxy: "{{ lookup('env','no_proxy') }}"
    HTTP_PROXY: "{{ lookup('env','http_proxy') }}"
    HTTPS_PROXY: "{{ lookup('env','https_proxy') }}"
    NO_PROXY: "{{ lookup('env','no_proxy') }}"
  pre_tasks:
    - name: Load distribution variables
      include_vars:
        file: "{{ item }}"
      with_items:
        - "{{ xci_path }}/xci/var/{{ ansible_os_family }}.yml"
        - "{{ xci_flavor_ansible_file_path }}/flavor-vars.yml"
    - name: Set facts for remote deployment
      set_fact:
        remote_xci_path: "{{ ansible_env.HOME }}/releng-xci"
        remote_xci_flavor_files: "{{ ansible_env.HOME }}/releng-xci/xci/installer/{{installer_type}}/files/{{ xci_flavor }}"
        remote_xci_playbooks: "{{ ansible_env.HOME }}/releng-xci/xci/playbooks"

  roles:
    - role: bootstrap-host
      configure_network: xci_flavor != 'aio'
    - role: peru.proxy_settings
      proxy_settings_http_proxy: "{{ lookup('env','http_proxy') }}"
      proxy_settings_https_proxy: "{{ lookup('env','https_proxy') }}"
      proxy_settings_ftp_proxy: "{{ lookup('env','ftp_proxy') }}"
      proxy_settings_no_proxy: "{{ lookup('env','no_proxy') }}"

  tasks:
    - name: Configure SSH key for root user
      user:
        name: root
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_comment: xci
        ssh_key_type: rsa
        state: present

    - name: Copy releng-xci to remote host
      synchronize:
        src: "{{ xci_path }}/"
        dest: "{{ remote_xci_path }}"
        recursive: yes
        delete: yes
    - name: copy flavor inventory
      command: "/bin/cp -rf {{ remote_xci_flavor_files }}/inventory {{ remote_xci_playbooks }}"
      args:
        creates: "{{ remote_xci_playbooks }}/inventory"
    - name: copy openstack_deploy
      command: "/bin/cp -rf {{openstack_osa_path}}/etc/openstack_deploy {{openstack_osa_etc_path}}"
      args:
        creates: "{{ openstack_osa_etc_path }}"
    - name: copy openstack_user_config.yml
      command: "/bin/cp -rf {{ remote_xci_flavor_files }}/openstack_user_config.yml {{openstack_osa_etc_path}}"
      args:
        creates: "{{ openstack_osa_etc_path }}/openstack_user_config.yml"
      failed_when: false
    - name: copy all user override files
      command: "/bin/cp -rf {{ remote_xci_flavor_files }}/user_variables.yml {{openstack_osa_etc_path}}"
      args:
        creates: "{{ openstack_osa_etc_path }}/user_variables.yml }}"
      failed_when: false
    - name: copy cinder.yml
      command: "/bin/cp -rf {{ remote_xci_path }}/xci/installer/osa/files/cinder.yml {{openstack_osa_etc_path}}/env.d"
      args:
        creates: "{{ openstack_osa_etc_path }}/env.d/cinder.yml"
    - name: Configure OpenStack-Ansible components
      lineinfile:
        path: "{{ openstack_osa_etc_path }}/user_variables.yml"
        line: "{{ item.component }}: {{ item.value }}"
        state: present
      with_items:
        - { component: "tempest_install", value: "{{ run_tempest | bool }}" }
        - { component: "tempest_run", value: "{{ run_tempest | bool }}" }
        - { component: "core_openstack", value: "{{ core_openstack_install | bool }}" }
    - block:
        - name: copy ceph.yml
          command: "/bin/cp -rf {{ remote_xci_flavor_files }}/ceph.yml {{openstack_osa_etc_path}}/conf.d/"
          args:
            creates: "{{ openstack_osa_etc_path }}/conf.d/ceph.yml"
        - name: copy user_ceph.yml
          command: "/bin/cp -rf {{ remote_xci_flavor_files }}/user_ceph.yml {{openstack_osa_etc_path}}/user_ceph.yml"
          args:
            creates: "{{ openstack_osa_etc_path }}/user_ceph.yml"
        - name: copy user_variables_ceph.yml
          command: "/bin/cp -rf {{ remote_xci_flavor_files }}/user_variables_ceph.yml {{openstack_osa_etc_path}}/user_variables_ceph.yml"
          args:
            creates: "{{ openstack_osa_etc_path }}/user_variables_ceph.yml"
      when: xci_ceph_enabled == "true"
    - block:
        - name: copy user_variables_proxy.yml
          command: "/bin/cp -rf {{ remote_xci_path }}/xci/installer/osa/files/user_variables_proxy.yml {{openstack_osa_etc_path}}/user_variables_proxy.yml"
          args:
            creates: "{{ openstack_osa_etc_path }}/user_variables_proxy.yml"
        - name: "Configure http_proxy_env_url"
          lineinfile:
            path: "{{openstack_osa_etc_path}}/user_variables_proxy.yml"
            regexp: "^http_proxy_env_url:.*"
            line: "{{ 'http_proxy_env_url: ' + lookup('env','http_proxy') }}"
      when:
        - lookup('env','http_proxy') != "randomfoobarstring"
    - name: copy OPNFV OpenStack playbook
      command: "/bin/cp -rf {{ remote_xci_path }}/xci/installer/osa/files/setup-openstack.yml {{openstack_osa_path}}/playbooks"
      args:
        creates: "{{ openstack_osa_path }}/playbooks/setup-openstack.yml"
    - name: copy pinned versions of OSA Roles and global requirements
      command: "/bin/cp -rf {{ remote_xci_path }}/xci/installer/osa/files/{{ item }} {{openstack_osa_path}}/{{ item }}"
      args:
        creates: "{{ openstack_osa_path }}/{{ item }}"
      with_items:
        - "ansible-role-requirements.yml"
        - "global-requirement-pins.txt"
      when:
        - openstack_osa_version != "master"
    - name: copy pinned versions of OpenStack services
      command: "/bin/cp -rf {{ remote_xci_path }}/xci/installer/osa/files/openstack_services.yml {{openstack_osa_path}}/playbooks/defaults/repo_packages/openstack_services.yml"
      args:
        creates: "{{ openstack_osa_path }}/playbooks/defaults/repo_packages/openstack_services.yml"
      when:
        - openstack_osa_version != "master"
    - include: "{{ xci_path }}/xci/playbooks/bootstrap-scenarios.yml"
    - name: bootstrap ansible on opnfv host
      command: "/bin/bash ./scripts/bootstrap-ansible.sh"
      changed_when: True
      args:
        chdir: "{{openstack_osa_path}}"
    - name: install opnfv pip required packages
      pip:
        name: "{{ item }}"
        state: present
        extra_args: '-c https://raw.githubusercontent.com/openstack/requirements/{{ requirements_git_install_branch }}/upper-constraints.txt'
      with_items:
        - pyyaml
        - python-neutronclient
        - python-openstackclient
    - name: Install ARA callback plugin in OSA virtualenv
      pip:
        name: ara
        state: present
        extra_args: '-c https://raw.githubusercontent.com/openstack/requirements/{{ requirements_git_install_branch }}/upper-constraints.txt'
        executable: '/opt/ansible-runtime/bin/pip'
    - name: Determine ARA callback location
      command: "/opt/ansible-runtime/bin/python -c 'import os,ara; print(os.path.dirname(ara.__file__))'"
      changed_when: False
      register: _ara_install_dir
    - name: Create local Ansible plugins directory
      file:
        path: "{{ ansible_env.HOME }}/.ansible/plugins/callback/ara"
        state: directory
    - name: Configure ARA callback
      file:
        path: "{{ ansible_env.HOME }}/.ansible/plugins/callback/ara/callbacks"
        src: "{{ _ara_install_dir.stdout }}/plugins/callbacks"
        force: yes
        state: link
    - name: generate password token
      command: "python pw-token-gen.py --file {{openstack_osa_etc_path}}/user_secrets.yml"
      args:
        chdir: "{{openstack_osa_path}}/scripts"
      changed_when: True
    - name: check if certificate directory /etc/ssl/certs exists already
      stat: path=/etc/ssl/certs
      register: check_etc_ssl_certs
    - name: create certificate directory /etc/ssl/certs
      file:
        path: "/etc/ssl/certs"
        state: directory
      when: check_etc_ssl_certs.stat.exists == false
    - name: create key directory /etc/ssl/private
      file:
        path: "/etc/ssl/private"
        state: directory
    - name: copy certificate to /etc/ssl/certs
      copy:
        src: "/etc/ssl/certs/xci.crt"
        dest: "/etc/ssl/certs/"
    - name: read remote key from /etc/ssl/private
      set_fact:
        xci_ssl_key: "{{ lookup('pipe', 'sudo cat /etc/ssl/private/xci.key' ) }}"
    - name: copy key to /etc/ssl/private
      copy:
        content: "{{ xci_ssl_key }}"
        dest: "/etc/ssl/private/xci.key"
      become: true
    - name: fetch xci environment
      copy:
        src: "{{ xci_path }}/.cache/xci.env"
        dest: /root/xci.env

    - name: Reload OpenStack-Ansible variables
      include_vars:
        file: "{{ xci_flavor_ansible_file_path }}/user_variables.yml"

    - name: Generate openrc
      include_role:
        name: "openstack-ansible-openstack_openrc"

    - name: add extra insecure flag to generated openrc
      blockinfile:
          dest: "{{ ansible_env.HOME }}/openrc"
          block: |
              export OS_INSECURE=true

    - name: fetch generated openrc
      fetch:
        src: "{{ ansible_env.HOME }}/openrc"
        dest: "{{ xci_path }}/.cache/openrc"
        flat: true

    - name: Determine local user
      become: no
      local_action: command whoami
      changed_when: False
      register: _ansible_user

    - name: Fetch local SSH key
      delegate_to: localhost
      become: no
      slurp:
        src: "/home/{{ _ansible_user.stdout }}/.ssh/id_rsa.pub"
      register: _local_ssh_key

    - name: Configure OPNFV authorized_keys file
      authorized_key:
        exclusive: yes
        user: root
        state: present
        manage_dir: yes
        comment: "{{ _ansible_user.stdout }} key"
        key: "{{ _local_ssh_key['content'] | b64decode }}"
